# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Drb < Formula
  desc "drb - Drone CI command line browser"
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/garbelini/drb/releases/download/v1.0.0/drb_1.0.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "08c704a9f3d37830c2f152f79804c65c82efa9ff10540ac84ca15aa7e3ffd80f"

    def install
      bin.install "drb"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Drb
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garbelini/drb/releases/download/v1.0.0/drb_1.0.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3310b6b39ee14a9c8fb772ed0611a9da819721f87c368e5d2fdf36daa89cf429"

      def install
        bin.install "drb"
      end
    end
  end
end
