# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class DroneView < Formula
  desc "Drone CI command line browser"
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/garbelini/drone-view/releases/download/v0.1.1/drone-view_0.1.1_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4cb5793a8e870506305d24b238027c53c1e59e42e606fa774ab2152cd3963a5a"

    def install
      bin.install "drone-view"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the DroneView
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garbelini/drone-view/releases/download/v0.1.1/drone-view_0.1.1_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3e36752a78ca07d5f9f109c71fe2cfd2d34331da2bea6306145d16b99841b08a"

      def install
        bin.install "drone-view"
      end
    end
  end
end
