# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private.rb"
class DroneView < Formula
  desc "Drone CI command line browser"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/garbelini/drone-view/releases/download/v0.1.0/drone-view_0.1.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "a6ec3844a30cb3fad9b24bc9dc8f6a5fa96714a7e60778a4d648b83e3765f32f"

    def install
      bin.install "drone-view"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the DroneView
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garbelini/drone-view/releases/download/v0.1.0/drone-view_0.1.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c3f234c9c5f88c7bd6e0688411901800cb3935caeb7ae1d5af58cf8fb95f2296"

      def install
        bin.install "drone-view"
      end
    end
  end
end
