# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class DroneView < Formula
  desc "Drone CI command line browser"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/garbelini/drone-view/releases/download/v0.1.0/drone-view_0.1.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4b6461172a19feb1894b1ef07f6e9b55ab71047d9d1543a24902969bc27bf3fe"

    def install
      bin.install "drone-view"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the DroneView
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garbelini/drone-view/releases/download/v0.1.0/drone-view_0.1.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "704916f3bc5a240fd999bc84299654d30d0b7bcfd4d7b7b764f25fc30d0b4fef"

      def install
        bin.install "drone-view"
      end
    end
  end
end
